AWSTemplateFormatVersion: '2010-09-09'
Description: 'google-calendar-service

  '
Globals:
  Function:
    Timeout: 60
Outputs:
  FetchEventsFunction:
    Description: Fetch Events Lambda Function ARN
    Value:
      Fn::GetAtt:
      - FetchEventsFunction
      - Arn
  FetchEventsFunctionIamRole:
    Description: Implicit IAM Role created for Fetch Events function
    Value:
      Fn::GetAtt:
      - FetchEventsFunctionRole
      - Arn
Resources:
  FetchEventsFunction:
    Properties:
      CodeUri: s3://timeframe-google-calendar-service/dc493e3ea3169c3f474efe9f35340598
      Handler: app.lambda_handler
      Runtime: ruby2.5
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
